-- SILAVET — sincronización aditiva de esquema
-- Generado por: php artisan lb:schema-sync
-- Modelo : lb_neolab
-- Destino: lb_lvm
-- Fecha  : 2026-08-28 16:24:36
--
-- ADITIVO: no elimina tablas/columnas ni modifica tipos existentes.
-- Ejecutar sobre la BD destino (USE `lb_lvm`).
-- Después: php artisan lb:switch <slug> && php artisan lb:migrate-legacy --force

SET FOREIGN_KEY_CHECKS = 0;

-- ---------------------------------------------------------------------------
-- Diferencias de tipo (NO se modifican; revisar a mano si hace falta)
-- ---------------------------------------------------------------------------
-- entorno.formulas
--   modelo : `formulas` text NOT NULL
--   destino: `formulas` mediumtext NOT NULL
-- entorno.e_AnchoPapel
--   modelo : `e_AnchoPapel` decimal(8,2) DEFAULT 80.00
--   destino: `e_AnchoPapel` float(6,2) DEFAULT NULL
-- entorno.e_AnchoEtiq
--   modelo : `e_AnchoEtiq` decimal(8,2) DEFAULT 35.00
--   destino: `e_AnchoEtiq` float(6,2) DEFAULT NULL
-- entorno.e_AltoEtiq
--   modelo : `e_AltoEtiq` decimal(8,2) DEFAULT 20.00
--   destino: `e_AltoEtiq` float(6,2) DEFAULT NULL
-- entorno.e_CantCol
--   modelo : `e_CantCol` tinyint(3) unsigned DEFAULT 2
--   destino: `e_CantCol` float(6,2) DEFAULT NULL
-- entorno.e_GapX
--   modelo : `e_GapX` decimal(8,2) DEFAULT 2.00
--   destino: `e_GapX` float(6,2) DEFAULT NULL
-- entorno.e_GapY
--   modelo : `e_GapY` decimal(8,2) DEFAULT 2.00
--   destino: `e_GapY` float(6,2) DEFAULT NULL
-- entorno.e_MarginTop
--   modelo : `e_MarginTop` decimal(8,2) DEFAULT 1.00
--   destino: `e_MarginTop` float(6,2) DEFAULT NULL
-- entorno.e_MarginBottom
--   modelo : `e_MarginBottom` decimal(8,2) DEFAULT 0.00
--   destino: `e_MarginBottom` float(6,2) DEFAULT NULL
-- entorno.e_MarginLeft
--   modelo : `e_MarginLeft` decimal(8,2) DEFAULT 2.00
--   destino: `e_MarginLeft` float(6,2) DEFAULT NULL
-- entorno.e_MarginRight
--   modelo : `e_MarginRight` decimal(8,2) DEFAULT 0.00
--   destino: `e_MarginRight` float(6,2) DEFAULT NULL
-- entorno.e_FontLinea1
--   modelo : `e_FontLinea1` tinyint(3) unsigned DEFAULT 18
--   destino: `e_FontLinea1` int(3) DEFAULT NULL
-- entorno.e_FontLinea2
--   modelo : `e_FontLinea2` tinyint(3) unsigned DEFAULT 12
--   destino: `e_FontLinea2` int(3) DEFAULT NULL
-- entorno.e_FontLinea3
--   modelo : `e_FontLinea3` tinyint(3) unsigned DEFAULT 11
--   destino: `e_FontLinea3` int(3) DEFAULT NULL
-- entorno.e_FontLinea4
--   modelo : `e_FontLinea4` tinyint(3) unsigned DEFAULT 8
--   destino: `e_FontLinea4` int(3) DEFAULT NULL
-- entorno.e_MaxLargoLinea2
--   modelo : `e_MaxLargoLinea2` tinyint(3) unsigned DEFAULT 21
--   destino: `e_MaxLargoLinea2` int(3) DEFAULT NULL
-- entorno.e_MaxLargoLinea3
--   modelo : `e_MaxLargoLinea3` tinyint(3) unsigned DEFAULT 25
--   destino: `e_MaxLargoLinea3` int(3) DEFAULT NULL
-- entorno.e_Borde
--   modelo : `e_Borde` tinyint(1) DEFAULT 0
--   destino: `e_Borde` int(1) DEFAULT NULL
-- itemsinforme.textos
--   modelo : `textos` text DEFAULT NULL
--   destino: `textos` mediumtext DEFAULT NULL
-- itemsinforme.idAnalizador
--   modelo : `idAnalizador` varchar(20) DEFAULT NULL
--   destino: `idAnalizador` varchar(50) DEFAULT NULL
-- pacientes.observaciones
--   modelo : `observaciones` text DEFAULT NULL
--   destino: `observaciones` mediumtext DEFAULT NULL
-- pacientes.clinica
--   modelo : `clinica` text DEFAULT NULL
--   destino: `clinica` mediumtext DEFAULT NULL
-- renglones.valor
--   modelo : `valor` text DEFAULT NULL
--   destino: `valor` mediumtext DEFAULT NULL
-- renglones.idAnalizador
--   modelo : `idAnalizador` varchar(20) DEFAULT NULL
--   destino: `idAnalizador` varchar(50) DEFAULT NULL
-- usuarios.cuit
--   modelo : `cuit` varchar(11) NOT NULL DEFAULT '0'
--   destino: `cuit` varchar(11) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL DEFAULT '0'
-- usuarios.razonSocial
--   modelo : `razonSocial` varchar(100) NOT NULL DEFAULT '0'
--   destino: `razonSocial` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL DEFAULT '0'
-- usuarios.domicComerc
--   modelo : `domicComerc` varchar(50) NOT NULL DEFAULT '0'
--   destino: `domicComerc` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL DEFAULT '0'
-- usuarios.condIva
--   modelo : `condIva` varchar(30) NOT NULL DEFAULT '0'
--   destino: `condIva` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL DEFAULT '0'
-- usuarios.ingresosBrutos
--   modelo : `ingresosBrutos` varchar(30) NOT NULL DEFAULT '0'
--   destino: `ingresosBrutos` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL DEFAULT '0'
-- usuarios.key
--   modelo : `key` varchar(100) NOT NULL DEFAULT '0'
--   destino: `key` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL DEFAULT '0'
-- usuarios.crt
--   modelo : `crt` varchar(100) NOT NULL DEFAULT '0'
--   destino: `crt` varchar(100) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL DEFAULT '0'

-- ---------------------------------------------------------------------------
-- Solo en destino (no se eliminan)
-- ---------------------------------------------------------------------------
-- columna extra: itemsinforme.mostrar
-- columna extra: pacientes.obsPagos

SET FOREIGN_KEY_CHECKS = 1;
